### PR TITLE
add option to pass in destination to homesick clone #141

### PR DESCRIPTION
**Pull request by rweng**
seems to work correctly:

```bash
homesick clone wfarr/dotfiles testrepo
   git clone  https://github.com/wfarr/dotfiles.git to /Users/rowe/.homesick/repos/testrepo
  ...

homesick list
     bash-it  https://github.com/rweng/bash-it.git
    testrepo  https://github.com/wfarr/dotfiles.git

```

### CODE REVIEW

**Comment by JCook21** [comment]
I like the concept of this in general but I don't like the way the decision on the destination is split over 4 or so lines in different places. Do you think this could be refactored as a value object or at least a method? That would allow us to encapsulate the logic and decision making on the destination into a single location. What do you think?

**Comment by rweng** [comment]
I agree, but as this was the state before I did not want to change too much as I'm new in the code. Also, I don't have time to refactor this right now. Could we do this as a separate refactoring pr, maybe? Otherwise just leave this issue open and I update the pr when I find some time to work on this further.

**Comment by JCook21** [comment]
Let's do it as a refactoring PR then. Feel free to submit a patch when you have time.

**Comment by JCook21** [comment]
Anyone else care to comment on this before I merge it? @rweng I don't doubt your code but would like to let anyone else comment before I merge this since it's a change to existing functionality. :)

**Comment by JCook21** [comment]
@technicalpickles @nicolasmccurdy @muratayusuke any comments or thoughts on this?

**Comment by JCook21** [comment]
In lieu of other comments and as this seemed to be a fairly small change I decided to merge this. I had to manually merge to resolve a few conflicts caused by my refactoring. Thanks @rweng.

**Pull request merged**
