### PR TITLE
add support for git fetch

### LINKED ISSUE #132: Add fetch command
I would like to have the `git fetch` command available through homesick.
This way I can do a `homesick fetch` to see if I am behind from the remote.

I have a homesick-all function in my [bash functions](https://github.com/Kidlike/homesick-bash/blob/master/home/.bash_functions) that will run the provided homesick arguments for all castles.

So then I could do a `homesick-all fetch` and immediately see if any of my castles need updating.

### PR DESCRIPTION
**Pull request by Kidlike**
closes #132

### CODE REVIEW

**Comment by JCook21** [comment]
I'm not totally sure about the use cases for this. You could achieve the same functionality through 'homesick cd' and then type 'git fetch' in the console. I'm not sure if we should support every possible git command in homesick but I am open to persuasion in this case. What does anyone else think?

**Comment by Kidlike** [comment]
Well, the code is already there :D

In any case. I don't want to have to do `homesick cd` and then `git fetch`. I have 5 castles, that would take forever.

I want to run '[homesick-all](https://github.com/Kidlike/homesick-bash/blob/master/home/.bash_functions) fetch' to see in 5 seconds if I have any incoming changes.

**Comment by JCook21** [comment]
That's fair. :) I'll wait to see if anyone else comments on this too but I can certainly see where you're coming from on this.

**Comment by JCook21** [comment]
I just had another look at this again and exactly the same functionality can be achieved using 'homesick exec_all git fetch'. I'm inclined to say that we can't mirror every single git function in homesick. I appreciate the PR but I think I'm going to give it a :-1: this time just because there is another way to do this.

**Comment by Kidlike** [comment]
wow.. didn't even know about exec_all !!!
That's brilliant thanks :)

Although, the same could apply to `homesick pull` as well. `homesick exec_all git pull`
But I'm fine anyway since I can do what I want.

**Comment by JCook21** [comment]
I agree there's some inconsistency there that we need to work out... :)

**Pull request closed without merging**
