### PR TITLE
Fix homesick open

### PR DESCRIPTION
**Pull request by rweng**
I don't get why my pull-request also includes @shioyama's commit, as it is based on master that should already contain the commit. However, output looks fine to me as destination is in there as well as my change. Please correct me if I'm wrong.

### CODE REVIEW

**Comment by JCook21** [comment]
Could this be broken into two PR's? I know the changes are minor but I'd like to keep this granular if possible.

**Comment by JCook21** [comment]
Wait, forget that last comment. That's what happens when I try to read PR's on my cellphone. Apologies.

**Comment by JCook21** [comment]
Not sure why @shioyama's commit his showing as part of this PR. Could you try rebasing on master to see if that fixes it?

**Comment by rweng** [comment]
jep that did it

**Pull request merged**
